### ISSUE TITLE
getParameters() is missing? 

### ISSUE THREAD

**Issue by idansc** [jnhwkim/cbp#11]
Hi, 

I'm getting poor performance after loading a gmodule containing a cbp for classification. 
It works well before I save(using torch.save) and load the module. 

I'm thinking something is wrong with the parameters after loading, but I'm not sure what exactly are the module parameters, for my understanding we only sample h and s. Should I reset the module then after each iteration or keep them fixed?  Am I missing something that might cause the loading problem?

Thanks!

**Comment by jnhwkim** [comment]
@idansc please keep them fixed, otherwise, you will get a definitely poor result. `getParameters()` does not count those parameters, similarly to BatchNormalization's `running_mean` and `running_var` parameters.
