### ISSUE TITLE
how to modify the code if dimemsion of input is 3?

### ISSUE THREAD

**Issue by cloud-waiting-for-wind** [jnhwkim/cbp#13]
I find this code can only handle the  input whose dimension is 2.
in the paper of Berkeley, they use cbp layer to do attention,  the input become 2048_14_14 or 2048_196, if the  batchsize  is 20, the input of cbp layer will become 20_2048_196      and the input  dimension will become 3.

I find    assert(false, '# of dimensions > 2')  in CompactBilinearPooling.lua.
how to modify the code if the dimemsion of input is 3 or more ?

**Comment by jnhwkim** [comment]
We can detour that issue using `nn.Reshape`. Please refer to [this model](https://github.com/jnhwkim/MulLowBiVQA/blob/master/netdef/MCB.lua). And refer to [a comment](https://github.com/akirafukui/vqa-mcb/issues/1) from one of authors.
