### ISSUE TITLE
How can I run the code with CPU?

### ISSUE THREAD

**Issue by thanhkien84** [jnhwkim/cbp#5]
Hi everyone, thank you for great code.
Can anyone tell me how to run the code with CPU only? I dont have GPU on my laptop and when I run the code, I got error "no CUDA-capable device is detected".
Thanks,
Kien.

**Comment by jnhwkim** [comment]
I'm sorry, for now implemented as GPU only. If you need, you can modify the convolution part as cpu version manually.

**Comment by iamaaditya** [comment]
Thanks to open source community, cudnn comes with convert function, which can be for most part be translated to equivalent functions in 'nn' package, which runs on CPU. See the description here https://github.com/soumith/cudnn.torch#conversion-between-cudnn-and-nn
