### ISSUE TITLE
is it possible to remove the depency on spectral-lib to make it a self-contained package here? 

### ISSUE THREAD

**Issue by eriche2016** [jnhwkim/cbp#9]

**Comment by eriche2016** [comment]
very excellent work, i am wondering if  we can remove the depencies on spectral-lib to make it more self-contained?

**Comment by jnhwkim** [comment]
@eriche2016 Thanks for your interest. Earnestly, I don't have much experience with CUDA programming, I had to use other suitable library for rapid experiment and deploy. The implementation of convolution used in this module is not implemented in `cunn` or `cudnn` package when I was searching.

If you can implement those features and send a pull request, I'll be very glad to review and merge.
